### ISSUE TITLE
求助，怎么安装使用？

### ISSUE THREAD

**Issue by qianyu661** [flymote/LMXCC#4]
大佬们有没有详细的安装教程参考呀。感谢🙏

**Comment by flymote** [comment]
有说明文档，但希望再详细吗。。。  这个本来就是按照应用平台的思路做的，不是一个简单的应用程序，开源只是希望给相应人员提供帮助，因为我里面有些东西本身就是从开源项目获取的，理应开源反馈回去；里面涉及东西比较多，对安装使用的人员的技术水平有一定要求的
